### ISSUE TITLE
fix `--df-swap` functionality for `bsf oci` cmd

### ISSUE THREAD

**Issue by rakshitgondwal** [buildsafedev/bsf#119]
We recently got rid of the `--dev` flag for the `bsf oci` command which broke the `--df-swap` functionality. We need to fix this.

**Comment by Bharadwajshivam28** [comment]
Hey @rakshitgondwal I would take on this issue btw can you pls provide me some info to get started

**Comment by rakshitgondwal** [comment]
Hey @Bharadwajshivam28!
I believe there are some blockers for this issue to be picked up yet. Will let you know once we've decided on how to tackle this.

cc @dr-housemd

**Comment by dr-housemd** [comment]
We've decided to remove the --df-swap flag in favour of using build args in Dockerfile and recommending users to pass the image names as build args.

**Comment by Bharadwajshivam28** [comment]
Is it ready to pick this issue? @rakshitgondwal @dr-housemd

**Comment by rakshitgondwal** [comment]
Yes, go ahead @Bharadwajshivam28

**Comment by rakshitgondwal** [comment]
Hey @Bharadwajshivam28, were you able to make any progress on this? Let me know if you need any help

**Comment by Bharadwajshivam28** [comment]
> Hey @Bharadwajshivam28, were you able to make any progress on this? Let me know if you need any help

Hello @rakshitgondwal 
I will look in this soon just quite busy will jump soon this Sunday
