### ISSUE TITLE
Add `bsf clean` command

### ISSUE THREAD

**Issue by rakshitgondwal** [buildsafedev/bsf#120]
It often gets untidy while developing for a new feature or testing out things locally to manually delete the autogenerated bsf files/dirs such as: `bsf/`, `bsf-result/`, `bsf.hcl`, `bsf.lock`.

We should have a `bsf clean` that should clean all these autogenerated files.

Note: This command should only work under the `BSF_DEBUG_MODE`.

We already have a cleanup logic under `cmd/init` so we can reuse that.

**Comment by Suraj-kumar00** [comment]
Hi @rakshitgondwal, how have you been?
I would like to work on this issue, can you please guide me a little bit?

**Comment by rakshitgondwal** [comment]
Hi @Suraj-kumar00, we need to create a new `bsf clean` command that will clean up all the autogenerated files. Only thing is that this command should be under the `BSF_DEBUG_MODE`. We have a a couple other commands under that such as `bsf precheck`, similarly `clean` should be implemented.
You can reuse this logic as well: https://github.com/buildsafedev/bsf/blob/a2c73d1a07c03290df94270b30c687bac5491b41/cmd/init/init.go#L150

**Comment by hanshal101** [comment]
Hey is this issue still up?
If yes I would like to work on it!

**Comment by rakshitgondwal** [comment]
Hey @hanshal101, you can go ahead and make a PR
