### ISSUE TITLE
Sort packages in `bsf.hcl`

### ISSUE THREAD

**Issue by rakshitgondwal** [buildsafedev/bsf#126]
When we add a package in `bsf.hcl` using `bsf search`, the package gets added to the end. We should have a sorting logic for this so that the packages are sorted out automatically.

**Comment by hanshal101** [comment]
Sorting in terms of alphabetical order?

**Comment by dr-housemd** [comment]
@hanshal101  yes.

**Comment by hanshal101** [comment]
Cool would like to work on this!

**Comment by hanshal101** [comment]
Well I have implemented this for the search command, but I wanted to ask when initialized for the first time should it sort the default packages also?
