### ISSUE TITLE
bsf update for non-semver packages 

### ISSUE THREAD

**Issue by dr-housemd** [buildsafedev/bsf#29]
We've got bsf update working for semver. From our database, we noticed ~80% of packages follow semver, only 97 follow strict calver and rest are considered "unknown". Opening this issue to track as 20% is significant amount.

I think following things need to be done:

Deeper analysis to see if various conventions of calver are used. Gut feel is there should be more calver conventions packages are following other than YYYY.MM.x.

Discuss with community if they would be happy if we update to latest package when a constraint is given and it's not semver or calver, typically indicating revision numbers, commit hashes,etc.

**Comment by dr-housemd** [comment]
As a stop gap solution, till we discover better ways to deal with calver and various version schemes, we can let the user configure to get the latest version of the software based on date. 

Solution :

* Add a new update strategy- this can be called major version or timestamp based updates. 
* This will have a new symbol associated `#`. 
* In case of semver package, when this is chosen- we'll pick the largest semver possible. 
* In case there package doesn't follow semver, we pick the latest package. We do not display minor or patch as update strategies when this happens.

**Comment by hanshal101** [comment]
working on this !!
