### ISSUE TITLE
Support for installation apart from Nix?

### ISSUE THREAD

**Issue by thebigbone** [buildsafedev/bsf#44]
Hello, you have an awesome project. It can be extremely helpful for secure development. I was wondering if there are any other ways to install apart from Nix?

**Comment by dr-housemd** [comment]
Hey @thebigbone  , thanks for checking it out. May we know why you're looking for a different way to install the bsf CLI? 

We're currently working on release functionality where artifacts(static binaries for now) released by bsf are stored in github releases and we auto generate a flake(Nix recipe to install software). We could similarly do this for other package managers at some point. However, as for BuildSafe itself- I'm curious why you're looking to avoid Nix. It's core part of the project.

**Comment by thebigbone** [comment]
> Hey @thebigbone , thanks for checking it out. May we know why you're looking for a different way to install the bsf CLI?
> 
> We're currently working on release functionality where artifacts(static binaries for now) released by bsf are stored in github releases and we auto generate a flake(Nix recipe to install software). We could similarly do this for other package managers at some point. However, as for BuildSafe itself- I'm curious why you're looking to avoid Nix. It's core part of the project.

Imo, just downloading the cli binary would be a lot quicker. Nix is quite good but other people might not want to install Nix just to try the `bsf`

**Comment by dr-housemd** [comment]
@thebigbone  if you want to avoid using Nix on your system at all costs, then unfortunately I don't think you'll find bsf useful.
bsf heavily relies on Nix being present on the system to function and enable tamper proof builds. Our goal with bsf is to remove the complexity & the hesitation with using Nix. Do you mind sharing what you don't like about installing it?

It's quite literally one command to [install](https://github.com/DeterminateSystems/nix-installer?tab=readme-ov-file#usage  
).

`curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install`

There is also a signed package for MacOS available by the nice folks at DetSys.

**Comment by thebigbone** [comment]
Hey, I am all in for Nix. I never had any problems, I was just saying it would be a good idea to have different installation mediums but it seems like Nix is a core part of `bsf` which I was not aware of.

**Comment by dr-housemd** [comment]
cheers, look forward to hearing your feedback at our Discord.
