### ISSUE TITLE
bsf update --check

### ISSUE THREAD

**Issue by dr-housemd** [buildsafedev/bsf#48]
Few users may not prefer having a GitHub app/bot and would instead prefer if their CI failed when there is an update available so they can run `bsf update` themselves to commit the changes. 

For this, we need a flag on `bsf update` command - `--check`. 

When packages can be updated, the command will exit with status code 1(which is what users can run in their CI).

**Comment by dr-housemd** [comment]
Hey @hanshal101 , thanks for showing interest. 

I would suggest making a function to compare the slices. We can then compare the config we read and the the `newPackages` after updates. 

If there is a change and user has passed the `check` flag, we can os.Exit(1). 

PS: only gotcha when comparing slices is that we can't do a reflect.DeepEqual or something like that because we cannot rely on ordering of the elements.

**Comment by hanshal101** [comment]
Cool, I'm thinking of creating a compare function - `func compareVersions(a,b []strings) bool {}`, here i would create a go slice something like this `count := make(map[string]int)` and here I'll add all the `key` as version and inc the number (for a []string), and in the same way I would dec for b, and if the map in the `count`  doesn't have a zero it would return false.

How does this sound?

**Comment by dr-housemd** [comment]
sounds good, we can discuss the specifics on a PR review. Thanks for picking this :)
