### ISSUE TITLE
bsf init to prompt for inputs. 

### ISSUE THREAD

**Issue by dr-housemd** [buildsafedev/bsf#74]
Currently, bsf init assumes based on the files in the directory, what the user wants and generates a bsf.hcl that a user can then edit. 

It would be nice if we prompted the user, similar to `docker init` about what they would like to do. For example, we can ask- 
"Would you like to build your application using Dockerfile?(y/n)" 
Assume, user selected "yes"
"What would you like the name of the base image to be?". 

Then the input can be added to bsf.hcl file directly. 

Similarly, if a user selected "no" for Dockerfiles. 
We could ask- 
"What type of project are you setting up? "
"Go"
"Poetry"
"Rust"
"JavaScript"

And further ask any details , if required.

**Comment by hanshal101** [comment]
I can work on this !!!
