### ISSUE TITLE
bsf dockerfile digests

### ISSUE THREAD

**Issue by dr-housemd** [buildsafedev/bsf#79]
In order to have reproducible builds, we need all inputs to be cryptographically verifiable. Most registries have mutable tags that can be an obstacle to that goal. 

We should have a command to let users run `bsf dockerfile digests Dockerfile`. 

This command will look for all the `FROM` statements, find the digests of images and replace the tag with it. 
For example if a Dockerfile has `FROM ttl.sh/app:v0.1` , it should be replaced with `FROM ttl.sh/app@sha256:...`.

**Comment by hanshal101** [comment]
Working on this !!!
