### ISSUE TITLE
no such file or directory errors

### ISSUE THREAD

**Issue by dr-housemd** [buildsafedev/bsf#8]
As Nix expects files to be checked into git to be copied into build sandbox, we need the user to add the files into git.  

```
       error: opening file '/nix/store/ldh55gbksw3zaga4nw72bznz48ygpkjv-source/Cargo.lock': No such file or directory
```

I think we could do things from bsf side:
1. When core files such Cargo.lock, go.mod, poetry.lock, etc aren't added to git, we can assume that user has not added their src code either and we should print a clear error message asking user to check in their files in git by `git add . ` or by making a commit. 

2. When we notice the warning from Nix that the git tree is dirty. Users typically aren't aware of what "dirty" implies. From bsf, we could stream the Nix std output and when we notice this warning, we can append it with "This implies you have not checked-in files in git work tree(hint: git add )" .

**Comment by Manik2708** [comment]
Can I work on this?

**Comment by rakshitgondwal** [comment]
Sure, go ahead @Manik2708
