### ISSUE TITLE
base image prompts should ask for which deps to add based on project type

### ISSUE THREAD

**Issue by dr-housemd** [buildsafedev/bsf#89]
When a user does a `bsf init` in a Go repo and they've opted-in for creating a base image, we should ask them - 

"Would you like to add common Go dependencies(compiler, linter, debugger, etc)?(Y/n)" 

If they say yes, we should add them to bsf.hcl. 
Similar for other languages. 

We already have the common dependencies listed here- https://github.com/buildsafedev/bsf/blob/13996a15ccc66cbf0c44f0b47c907f1c0567531a/cmd/init/config.go#L133

We just need to avoid generating the App modules when user has selected base image.

**Comment by utsab818** [comment]
Hey, I would love to try out this issue.
Would you please guide me by providing more information about this?

**Comment by dr-housemd** [comment]
Hey @utsab818 , I've assigned the issue to you. Feel free to start a thread over at discord if you have any questions or need help with it
